import type { ExportContext, ExportPreset, ExportResult } from "../types.js";

/**
 * Generates AGENTS.md — a universal format documenting all agents and skills.
 */
export const agentsMdPreset: ExportPreset = {
  name: "agents-md",
  description: "Export as AGENTS.md (universal agent reference)",

  generate(context: ExportContext): ExportResult {
    const sections: string[] = [];
    sections.push("# AGENTS.md — Generated by fama-agents\n");
    sections.push(
      "> This file documents the AI agents and skills configured for this project.\n",
    );

    if (context.stack) {
      sections.push("## Tech Stack\n");
      if (context.stack.languages.length > 0)
        sections.push(`- **Languages:** ${context.stack.languages.join(", ")}`);
      if (context.stack.frameworks.length > 0)
        sections.push(`- **Frameworks:** ${context.stack.frameworks.join(", ")}`);
      if (context.stack.buildTools.length > 0)
        sections.push(`- **Build Tools:** ${context.stack.buildTools.join(", ")}`);
      if (context.stack.testFrameworks.length > 0)
        sections.push(`- **Test Frameworks:** ${context.stack.testFrameworks.join(", ")}`);
      if (context.stack.packageManagers.length > 0)
        sections.push(`- **Package Managers:** ${context.stack.packageManagers.join(", ")}`);
      if (context.stack.databases.length > 0)
        sections.push(`- **Databases:** ${context.stack.databases.join(", ")}`);
      sections.push("");
    }

    sections.push("## Agents\n");
    sections.push("| Agent | Description | Phases | Model |");
    sections.push("|-------|-------------|--------|-------|");
    for (const agent of context.agents) {
      const icon = agent.persona?.icon ? `${agent.persona.icon} ` : "";
      // Escape pipe characters and newlines to prevent table breakage
      const desc = agent.description.replace(/\|/g, "\\|").replace(/\n/g, " ");
      sections.push(
        `| ${icon}${agent.slug} | ${desc} | ${agent.phases.join(",")} | ${agent.model} |`,
      );
    }
    sections.push("");

    for (const agent of context.agents) {
      const icon = agent.persona?.icon ? `${agent.persona.icon} ` : "";
      sections.push(`### ${icon}${agent.name}\n`);
      sections.push(`> ${agent.description}\n`);

      if (agent.persona) {
        if (agent.persona.role) sections.push(`**Role:** ${agent.persona.role}`);
        if (agent.persona.identity) sections.push(`**Identity:** ${agent.persona.identity}`);
        if (agent.persona.communicationStyle)
          sections.push(`**Style:** ${agent.persona.communicationStyle}`);
      }

      if (agent.criticalActions && agent.criticalActions.length > 0) {
        sections.push(`\n**Critical Actions:**`);
        for (const action of agent.criticalActions) sections.push(`- ${action}`);
      }

      if (agent.defaultSkills.length > 0) {
        sections.push(`\n**Skills:** ${agent.defaultSkills.join(", ")}`);
      }

      sections.push(`\n**Tools:** ${agent.tools.join(", ")}`);
      sections.push("");
    }

    if (context.skills.length > 0) {
      sections.push("## Skills\n");
      sections.push("| Skill | Description | Phases |");
      sections.push("|-------|-------------|--------|");
      for (const skill of context.skills) {
        const desc = skill.description.replace(/\|/g, "\\|").replace(/\n/g, " ");
        sections.push(
          `| ${skill.slug} | ${desc} | ${skill.phases.join(",")} |`,
        );
      }
      sections.push("");
    }

    const content = sections.join("\n");

    return {
      files: [{ path: "AGENTS.md", content }],
      summary: "Generated AGENTS.md",
    };
  },
};
