import type { ExportContext, ExportPreset, ExportResult } from "../types.js";

/**
 * Generates .github/copilot-instructions.md for GitHub Copilot.
 */
export const copilotPreset: ExportPreset = {
  name: "copilot",
  description: "Export as .github/copilot-instructions.md",

  generate(context: ExportContext): ExportResult {
    const sections: string[] = [];
    sections.push("# Copilot Instructions — Generated by fama-agents\n");

    if (context.stack) {
      const stackParts: string[] = [];
      if (context.stack.languages.length > 0)
        stackParts.push(`**Languages:** ${context.stack.languages.join(", ")}`);
      if (context.stack.frameworks.length > 0)
        stackParts.push(`**Frameworks:** ${context.stack.frameworks.join(", ")}`);
      if (context.stack.buildTools.length > 0)
        stackParts.push(`**Build Tools:** ${context.stack.buildTools.join(", ")}`);
      if (context.stack.testFrameworks.length > 0)
        stackParts.push(`**Test Frameworks:** ${context.stack.testFrameworks.join(", ")}`);
      if (stackParts.length > 0) {
        sections.push("## Tech Stack\n");
        sections.push(stackParts.join("\n"));
        sections.push("");
      }
    }

    // Collect all critical actions
    const allCriticalActions: string[] = [];
    for (const agent of context.agents) {
      if (agent.criticalActions) {
        allCriticalActions.push(...agent.criticalActions);
      }
    }

    if (allCriticalActions.length > 0) {
      sections.push("## Critical Rules\n");
      const unique = [...new Set(allCriticalActions)];
      for (const action of unique) {
        sections.push(`- ${action}`);
      }
      sections.push("");
    }

    // Collect all principles
    const allPrinciples: string[] = [];
    for (const agent of context.agents) {
      if (agent.persona?.principles) {
        allPrinciples.push(...agent.persona.principles);
      }
    }

    if (allPrinciples.length > 0) {
      sections.push("## Development Principles\n");
      const unique = [...new Set(allPrinciples)];
      for (const principle of unique) {
        sections.push(`- ${principle}`);
      }
      sections.push("");
    }

    if (context.skills.length > 0) {
      sections.push("## Skills Reference\n");
      for (const skill of context.skills) {
        sections.push(`### ${skill.name}\n`);
        sections.push(skill.content);
        sections.push("");
      }
    }

    const content = sections.join("\n");

    return {
      files: [{ path: ".github/copilot-instructions.md", content }],
      summary: "Generated .github/copilot-instructions.md",
    };
  },
};
