import type { ExportContext, ExportPreset, ExportResult } from "../types.js";

/**
 * Generates a consolidated .windsurfrules file for Windsurf IDE.
 */
export const windsurfPreset: ExportPreset = {
  name: "windsurf",
  description: "Export agents as consolidated .windsurfrules",

  generate(context: ExportContext): ExportResult {
    const sections: string[] = [];
    sections.push("# Windsurf Rules — Generated by fama-agents\n");

    if (context.stack) {
      const stackParts: string[] = [];
      if (context.stack.languages.length > 0)
        stackParts.push(`Languages: ${context.stack.languages.join(", ")}`);
      if (context.stack.frameworks.length > 0)
        stackParts.push(`Frameworks: ${context.stack.frameworks.join(", ")}`);
      if (stackParts.length > 0) {
        sections.push(`## Tech Stack\n`);
        for (const part of stackParts) sections.push(`- ${part}`);
        sections.push("");
      }
    }

    sections.push("## Agents\n");

    for (const agent of context.agents) {
      const icon = agent.persona?.icon ? `${agent.persona.icon} ` : "";
      sections.push(`### ${icon}${agent.name}\n`);
      sections.push(agent.description);

      if (agent.criticalActions && agent.criticalActions.length > 0) {
        sections.push(`\n**Critical Actions:**`);
        for (const action of agent.criticalActions) {
          sections.push(`- ${action}`);
        }
      }

      sections.push(`\n---\n`);
    }

    if (context.skills.length > 0) {
      sections.push("## Skills\n");
      for (const skill of context.skills) {
        sections.push(`### ${skill.name}\n`);
        sections.push(skill.description);
        sections.push("");
      }
    }

    const content = sections.join("\n");

    return {
      files: [{ path: ".windsurfrules", content }],
      summary: "Generated .windsurfrules",
    };
  },
};
