name: code-review
description: "Code review completo: analise estatica, revisao profunda e relatorio"
outputDir: .fama/workflow-output/code-review

steps:
  - name: static-analysis
    description: "Analise estatica, lint e verificacao de tipos"
    agent: code-reviewer
  - name: deep-review
    description: "Revisao profunda de logica, seguranca e performance"
    agent: security-auditor
  - name: report
    description: "Relatorio consolidado de findings"
    agent: code-reviewer
